language: swift
osx_image: xcode9

script: 
  - set -o pipefail && xcodebuild -project "RxSugar.xcodeproj" -scheme "RxSugar-iOS" -destination "platform=iOS Simulator,name=iPhone X,OS=latest" build test | xcpretty --color --test
  - set -o pipefail && xcodebuild -project "RxSugar.xcodeproj" -scheme "RxSugar-tvOS" -destination "platform=tvOS Simulator,name=Apple TV 1080p,OS=latest" build test | xcpretty --color --test
